### ISSUE TITLE
How To Use Same API Calls For Native Apps

### ISSUE THREAD

**Issue by posherry** [gzoreslav/react-redux-saga-universal-application#22]
Is there a way to use the same API calls with watchers for native apps by changing templates? That would make it truly universal.

**Comment by gzoreslav** [comment]
Hi @posherry , are you talking about  React Native?

**Comment by posherry** [comment]
Hi @gzoreslav , Yes React Native...

**Comment by gzoreslav** [comment]
I do not have much experience with React Native. You may create merge request with this functionality  and I'll merge it

**Comment by posherry** [comment]
Sure! I'll make a merge request I manage it in the same codebase...
