### ISSUE TITLE
Server Side Rendering components different than actual components

### ISSUE THREAD

**Issue by ajeetvarma** [gzoreslav/react-redux-saga-universal-application#23]
While doing my application based on this boilerplate , i found that SSR components are  different than actual components . Even In the default example of `Media` When I searched contents after enter a keyword in input field , like example 'React' , In Client Side i found the required searched content related 
 topic of `React` but on viewing page source it is coming as default previous page contents . It actually does not change as per new client page contents.  

Please Suggest some idea regarding this ...

Thanks a lot ..

**Comment by ajeetvarma** [comment]
Sorry , There was wrong approach in my code . I have resolved it ..

**Comment by gzoreslav** [comment]
Thanks for using this starter!
