### ISSUE TITLE
React Selectize not working 

### ISSUE THREAD

**Issue by ajeetvarma** [gzoreslav/react-redux-saga-universal-application#24]
I have a requirement of [react-selectize](https://github.com/furqanZafar/react-selectize). I follow its documentation but unfortunately there is some type following errors coming as below ..

>  Element ref was specified as a string (select) but no owner was set. You may have multiple copies of React loaded.

While when i used in different package (latest create-react-app)  it is working fine . Please give me some help so that i can resolve my issue ..

Thanks a lot ..

**Comment by gzoreslav** [comment]
It is because I moved react-redux-saga-server-side-render-helper to separate package. You may not to use this package and just copy sources from https://github.com/gzoreslav/react-redux-saga-server-side-render-helper/tree/master/src directly to your sources.

I will do it in new versions

**Comment by ajeetvarma** [comment]
Thanks a lot @gzoreslav .  It works .  and also free of [https://github.com/gzoreslav/react-redux-saga-server-side-render-helper](https://github.com/gzoreslav/react-redux-saga-server-side-render-helper). Hope new versions come soon ...

:+1:
